name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Install golang-migrate
        run: |
          curl -L -o migrate.zip https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate-4.18.1.zip
          unzip migrate.zip
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate

      - name: Run migration
        run: make migrateup

      - name: Test
        run: make test
